root: ./docs/

​structure:
    readme: README.md
    summary: SUMMARY.md​

redirects:
    javascript-and-and-react: ./resources/README.md
    javascript-and-and-react/: ./resources/README.md
    javascript-and-react: ./resources/README.md
    javascript-and-react/: ./resources/README.md
    deployment/deploy-on-now: ./deployment/deploy-using-vercel.md
    deployment/deploy-on-now/: ./deployment/deploy-using-vercel.md
    installation-and-deploy/deploy-on-now: ./deployment/deploy-using-vercel.md
    installation-and-deploy/deploy-on-now/: ./deployment/deploy-using-vercel.md
    deployment/deploy-using-now-vercel: ./deployment/deploy-using-vercel.md
    deployment/deploy-using-now-vercel/: ./deployment/deploy-using-vercel.md
    installation-and-deploy: ./deployment/README.md
    installation-and-deploy/: ./deployment/README.md
    key-differences-with-gatsbyjs: ./about/README.md
    key-differences-with-gatsbyjs/: ./about/README.md
    installation-and-deploy/possible-architectures: ./architecture/README.md
    installation-and-deploy/possible-architectures/: ./architecture/README.md
    architecture: ./architecture/README.md
    architecture/: ./architecture/README.md
    faq: ./faq/README.md
    faq/: .faq/README.md
    showcases: https://frontity.org/showcase/
    showcases/: https://frontity.org/showcase/
    frontity-cli/create.md: ./frontity-cli/create-commands.md
    frontity-cli/create-package.md: ./frontity-cli/create-commands.md
    frontity-cli/build.md: ./frontity-cli/build-commands.md
    frontity-cli/dev.md: ./frontity-cli/run-commands.md
    frontity-cli/serve.md: ./frontity-cli/run-commands.md
    frontity-cli/info.md: ./frontity-cli/extra-commands.md
    frontity-cli/subscribe.md: ./frontity-cli/extra-commands.md
    resources: ./guides/README.md
    key-concepts: ./guides/README.md
    key-concepts/javascript: ./guides/javascript-basics.md
    key-concepts/react: ./guides/react-basic.md
    troubleshooting: ./guides/troubleshooting.md
    seo: ./guides/seo.md
    getting-started/connecting-to-wordpress.md: https://docs.frontity.org/getting-started/quick-start-guide#set-your-own-wordpress-installation
    getting-started/connecting-to-wordpress: https://docs.frontity.org/getting-started/quick-start-guide#set-your-own-wordpress-installation
    guides/link-prefetching.md: ./performance/link-prefetching.md
    learning-frontity/code-splitting.md: ./performance/code-splitting.md